In [1]:
import ir_datasets
from nltk.stem import WordNetLemmatizer
import nltk
from helper import create_tokenized_word_list

dataset = ir_datasets.load("wikir/en1k/training")
tokenized = create_tokenized_word_list(dataset)

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
nltk.download("punkt_tab")
nltk.download("wordnet")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /home/tahas44/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [3]:
lemmatized_tokenized_docs = []
lematizer = WordNetLemmatizer()

for query_list in tokenized:
    lemmatized_words = [lematizer.lemmatize(word) for word in query_list]
    lemmatized_tokenized_docs.append(lemmatized_words)

print("Docs lemmatized")

Docs lemmatized


In [4]:
from helper import create_tokenized_word_list_for_query
query_tokenized = create_tokenized_word_list_for_query(dataset)
print("Queries tokenized!")

Queries tokenized!


[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [5]:
lemmatized_tokenized_queries = []

for query_list in query_tokenized:
    lemmatized_words = [lematizer.lemmatize(words) for words in query_list]
    lemmatized_tokenized_queries.append(lemmatized_words)

print("Queries lemmatized")

Queries lemmatized


In [6]:
from rank_bm25 import BM25Okapi
bm25 = BM25Okapi(lemmatized_tokenized_docs)

In [7]:
scores_of_all_queries = []

for query in lemmatized_tokenized_queries:
    scores_of_all_queries.append(bm25.get_scores(query))

In [8]:
scores_of_all_queries

[array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 2.57180991, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([ 0.        ,  0.        , 11.54430976, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.43415237, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([4.88534099, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shap

In [9]:
from collections import defaultdict
from helper import Scoredoc

doc_dict = defaultdict(str)

for i, doc in enumerate(dataset.docs_iter()):
    doc_dict[i] = doc.doc_id

doc_dict = dict(doc_dict)

qrels_dict = defaultdict(list)

for qrel in dataset.qrels_iter():
    qrels_dict[qrel.query_id].append(qrel.doc_id)

qrels_dict = dict(qrels_dict)

score_doc_dict = defaultdict(list)

for scoreddoc in dataset.scoreddocs_iter():
    doc_id = scoreddoc.doc_id
    score = scoreddoc.score

    scoreddoc_object = Scoredoc(doc_id, score)

    score_doc_dict[scoreddoc.query_id].append(scoreddoc_object)

score_doc_dict = dict(score_doc_dict)

print("Necessary dicts created!")

Necessary dicts created!


In [10]:
query_ids = [query.query_id for query in dataset.queries_iter()]
query_ids

['123839',
 '188629',
 '13898',
 '316959',
 '515031',
 '123783',
 '4332',
 '9591',
 '114982',
 '563603',
 '104206',
 '1580851',
 '23678',
 '37480',
 '109454',
 '544250',
 '12519',
 '115015',
 '84287',
 '24998',
 '11925',
 '643',
 '113075',
 '1250387',
 '72012',
 '167865',
 '1425120',
 '24883',
 '27200',
 '136856',
 '6031',
 '1313191',
 '187115',
 '84110',
 '208234',
 '6431',
 '10799',
 '1417144',
 '32512',
 '677637',
 '97937',
 '113765',
 '12900',
 '1294909',
 '73745',
 '11692',
 '22173',
 '76662',
 '164301',
 '23344',
 '9367',
 '592217',
 '98546',
 '98175',
 '15189',
 '1256',
 '1815937',
 '1249076',
 '80274',
 '38489',
 '11311',
 '4754',
 '257711',
 '141668',
 '100895',
 '32945',
 '112321',
 '133725',
 '424464',
 '523456',
 '1327515',
 '12101',
 '9739',
 '189869',
 '143444',
 '78940',
 '12527',
 '327199',
 '7707',
 '97455',
 '1262433',
 '488875',
 '74026',
 '358108',
 '95179',
 '7862',
 '151797',
 '92980',
 '100876',
 '238228',
 '107755',
 '32539',
 '12953',
 '24843',
 '119528',
 '307

In [11]:
from collections import defaultdict

query_id_vs_text = defaultdict(str)

for query in dataset.queries_iter():
    query_id_vs_text[query.query_id] = query.text

In [12]:
import numpy as np
query_id_and_its_doc = defaultdict(list)

for i in range(len(query_ids)):
    found_doc_list = []
    similarity = scores_of_all_queries[i]

    index_of_found_docs = np.where(similarity > 0)[0]

    for index in list(index_of_found_docs):
        found_doc_list.append((similarity[index], doc_dict[index]))

    if len(found_doc_list) <= 10:
        for mytuple in found_doc_list:
            query_id_and_its_doc[query_ids[i]].append(mytuple[1])
    else:
        for mytuple in sorted(found_doc_list, reverse=True):
            query_id_and_its_doc[query_ids[i]].append(mytuple[1])

            if len(query_id_and_its_doc[query_ids[i]]) == 10:
                break

In [13]:
query_id_and_its_doc

defaultdict(list,
            {'123839': ['806300',
              '123839',
              '806326',
              '836567',
              '806075',
              '1793430',
              '806263',
              '799188',
              '1727316',
              '1901730'],
             '188629': ['188629',
              '2185399',
              '2191096',
              '2304431',
              '1046396',
              '1990307',
              '2296288',
              '533438',
              '2290269',
              '221705'],
             '13898': ['13898',
              '2213954',
              '1921403',
              '2108627',
              '1874948',
              '525283',
              '2216860',
              '2248373',
              '1440180',
              '1698181'],
             '316959': ['316959',
              '348869',
              '1836641',
              '2156815',
              '930698',
              '1326263',
              '2215542',
              '1525222',
      

In [14]:
doc_id_vs_text = defaultdict(str)

for doc in dataset.docs_iter():
    doc_id_vs_text[doc.doc_id] = doc.text

In [15]:
import gc 
del dataset
del tokenized
del lematizer
del lemmatized_tokenized_docs
del lemmatized_tokenized_queries
del lemmatized_words
del query_tokenized
del bm25
gc.collect()

0

In [16]:
query_doc_pairs = defaultdict(list)

for query_id in query_ids:
    for doc_id in query_id_and_its_doc[query_id]:
        query_doc_pairs[query_id].append((query_id_vs_text[query_id], doc_id_vs_text[doc_id]))

In [17]:
query_doc_pairs["123839"]

[('yanni',
  'it is a compilation of tracks from his five previous studio albums released between 1980 and 1989 plus three new compositions yanni was encouraged to release the album by his then partner actress linda evans reflections of passion became yanni s fastest selling and most successful album of his career upon release it reached no 1 on the billboard top new age albums chart and no 29 on the billboard 200 yanni supported the album with a nationwide concert tour in 1990 that featured his band and an orchestra in 1995 it was certified double platinum for selling 2 million copies in the us in august 1989 yanni released his fifth studio album niki nana the album marked his stylistic development from solo keyboard music towards rock with the addition of additional vocalists musicians and choir around the same time of its release yanni s newfound relationship with american actress linda evans who had become a fan of his music received press attention not long into their relationship

In [18]:
len(query_doc_pairs.keys())

1442

In [19]:
len(query_ids)

1444

In [20]:
from sentence_transformers import CrossEncoder
model = CrossEncoder('cross-encoder/ms-marco-MiniLM-L6-v2')

Loading weights: 100%|██████████| 105/105 [00:00<00:00, 13192.01it/s]


In [21]:
dict_keys_set = set(query_doc_pairs.keys())

In [22]:
scores = model.predict([
    ("How many people live in Berlin?", "Berlin had a population of 3,520,031 registered inhabitants in an area of 891.82 square kilometers."),
    ("How many people live in Berlin?", "Berlin is well known for its museums."),
])
print(scores)

[ 8.607138 -4.320079]


In [23]:
type(scores)

numpy.ndarray

In [25]:
list(scores)

[np.float32(8.607138), np.float32(-4.320079)]

In [27]:
query_score_dict = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        query_score_dict[query_id] = list(model.predict(query_doc_pairs[query_id]))

In [28]:
query_score_dict["123839"]

[np.float32(6.4627924),
 np.float32(6.419842),
 np.float32(4.9677753),
 np.float32(3.0357656),
 np.float32(5.5189133),
 np.float32(2.3268332),
 np.float32(4.384878),
 np.float32(0.7513137),
 np.float32(-3.6361036),
 np.float32(-4.7235107)]

In [29]:
del query_doc_pairs
gc.collect()

2425

In [49]:
most_related_5_dict = defaultdict(list)
most_related_5_dict_with_scores = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        related_10 = []

        for i, score in enumerate(query_score_dict[query_id]):
            related_10.append((score, i))

        for mytuple in sorted(related_10, reverse=True):
            most_related_5_dict[query_id].append(query_id_and_its_doc[query_id][mytuple[1]])
            most_related_5_dict_with_scores[query_id].append((query_id_and_its_doc[query_id][mytuple[1]], mytuple[0]))

            if len(most_related_5_dict[query_id]) == 5:
                break

In [65]:
most_related_10_dict = defaultdict(list)
most_related_10_dict_with_scores = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        related_10 = []

        for i, score in enumerate(query_score_dict[query_id]):
            related_10.append((score, i))

        for mytuple in sorted(related_10, reverse=True):
            most_related_10_dict[query_id].append(query_id_and_its_doc[query_id][mytuple[1]])
            most_related_10_dict_with_scores[query_id].append((query_id_and_its_doc[query_id][mytuple[1]], mytuple[0]))

            if len(most_related_10_dict[query_id]) == 10:
                break

In [31]:
most_related_5_dict

defaultdict(list,
            {'123839': ['806300', '123839', '806075', '806326', '806263'],
             '188629': ['188629', '2185399', '1990307', '2304431', '2191096'],
             '13898': ['13898', '2213954', '1698181', '1921403', '525283'],
             '316959': ['316959', '1326263', '930698', '348869', '1294742'],
             '515031': ['515031', '888195', '832086', '887826', '1376470'],
             '123783': ['1210005', '1209576', '123783', '579503', '1209561'],
             '4332': ['4332', '1442076', '989116', '1516841', '1815319'],
             '9591': ['143444', '1898638', '2416624', '2250838', '1966629'],
             '114982': ['2305139', '2305216', '1341103', '1191721', '917379'],
             '563603': ['12846', '563603', '349302', '270469', '373237'],
             '104206': ['1281151', '1972988', '104018', '149391', '200511'],
             '1580851': ['1549040',
              '2218736',
              '2187550',
              '1528190',
              '2279707'],
   

In [32]:
def recall(found_docs: list, test_list: list) -> float:
    counter = 0
    test_set = set(test_list)

    for doc_id in found_docs:
        if doc_id in test_set:
            counter += 1

    return (counter / len(test_list)) * 100

In [40]:
def precision(found_docs: list, test_list: list) -> float:
    counter = 0
    test_set = set(test_list)

    for doc_id in found_docs:
        if doc_id in test_set:
            counter += 1

    return (counter / len(found_docs)) * 100

In [66]:
def precision_AP(found_docs: list, test_list: list) -> float:
    counter = 0

    test_set = set(test_list)

    for doc in found_docs:
        if doc in test_set:
            counter += 1

    return counter / len(found_docs)


def AP(found_docs: list, test_list: list) -> float:
    total = 0

    for i in range(1, 10 + 1):
        if i < len(found_docs):
            precision_k = precision_AP(found_docs[:i], test_list)
            total += precision_k * (found_docs[i - 1] in set(test_list))

    return total / len(test_list)

In [41]:
recall_5_list, precision_5_list, AP_5_list = [], [], []

for query_id in query_ids:
    if query_id in dict_keys_set:
        recall_5_value = recall(most_related_5_dict[query_id], qrels_dict[query_id])
        precision_5_value = precision(most_related_5_dict[query_id], qrels_dict[query_id])
        AP_5_value = AP(most_related_5_dict[query_id], qrels_dict[query_id])

        recall_5_list.append(recall_5_value)
        precision_5_list.append(precision_5_value)
        AP_5_list.append(AP_5_value)
    else:
        recall_5_list.append(0)
        precision_5_list.append(0)
        AP_5_list.append(0)

In [67]:
recall_10_list, precision_10_list, AP_10_list = [], [], []

for query_id in query_ids:
    if query_id in dict_keys_set:
        recall_10_value = recall(most_related_10_dict[query_id], qrels_dict[query_id])
        precision_10_value = precision(most_related_10_dict[query_id], qrels_dict[query_id])
        AP_10_value = AP(most_related_10_dict[query_id], qrels_dict[query_id])

        recall_10_list.append(recall_10_value)
        precision_10_list.append(precision_10_value)
        AP_10_list.append(AP_10_value)
    else:
        recall_10_list.append(0)
        precision_10_list.append(0)
        AP_10_list.append(0)

In [42]:
recall_5_list

[66.66666666666666,
 33.33333333333333,
 33.33333333333333,
 22.22222222222222,
 7.142857142857142,
 26.666666666666668,
 8.333333333333332,
 0.322234156820623,
 16.666666666666664,
 4.081632653061225,
 0.0,
 0.0,
 50.0,
 22.22222222222222,
 28.57142857142857,
 33.33333333333333,
 33.33333333333333,
 62.5,
 16.666666666666664,
 8.333333333333332,
 0.6172839506172839,
 11.11111111111111,
 14.285714285714285,
 18.181818181818183,
 30.0,
 27.27272727272727,
 57.14285714285714,
 22.22222222222222,
 5.555555555555555,
 33.33333333333333,
 5.714285714285714,
 14.285714285714285,
 16.666666666666664,
 6.451612903225806,
 14.285714285714285,
 12.5,
 11.11111111111111,
 0.0,
 0.0,
 18.181818181818183,
 15.384615384615385,
 10.0,
 0.0,
 0.0,
 3.8461538461538463,
 33.33333333333333,
 12.5,
 3.8461538461538463,
 0.0,
 25.0,
 2.4390243902439024,
 33.33333333333333,
 16.666666666666664,
 16.666666666666664,
 4.166666666666666,
 4.761904761904762,
 16.666666666666664,
 16.666666666666664,
 8.33333333

In [43]:
len(recall_5_list)

1444

In [44]:
len(precision_5_list)

1444

In [68]:
recall_10_list

[100.0,
 33.33333333333333,
 33.33333333333333,
 22.22222222222222,
 14.285714285714285,
 33.33333333333333,
 8.333333333333332,
 0.5370569280343717,
 25.0,
 7.142857142857142,
 16.666666666666664,
 7.6923076923076925,
 50.0,
 44.44444444444444,
 28.57142857142857,
 33.33333333333333,
 66.66666666666666,
 87.5,
 16.666666666666664,
 8.333333333333332,
 0.6172839506172839,
 11.11111111111111,
 14.285714285714285,
 18.181818181818183,
 30.0,
 27.27272727272727,
 85.71428571428571,
 22.22222222222222,
 5.555555555555555,
 33.33333333333333,
 11.428571428571429,
 14.285714285714285,
 33.33333333333333,
 16.129032258064516,
 14.285714285714285,
 12.5,
 11.11111111111111,
 0.0,
 0.0,
 31.818181818181817,
 38.46153846153847,
 20.0,
 14.285714285714285,
 1.1904761904761905,
 7.6923076923076925,
 50.0,
 25.0,
 7.6923076923076925,
 0.0,
 37.5,
 2.4390243902439024,
 33.33333333333333,
 16.666666666666664,
 16.666666666666664,
 4.166666666666666,
 7.142857142857142,
 16.666666666666664,
 50.0,
 8.

In [69]:
len(recall_10_list)

1444

In [48]:
import pandas as pd

df = pd.DataFrame({
    "Query_ID": query_ids,
    "recall_5": recall_5_list,
    "precision_5": precision_5_list,
    "AP_5": AP_5_list
})

df

,Query_ID,recall_5,precision_5,AP_5
0,123839,66.666667,80.0,0.500000
1,188629,33.333333,40.0,0.333333
2,13898,33.333333,40.0,0.333333
3,316959,22.222222,40.0,0.222222
4,515031,7.142857,20.0,0.071429
...,...,...,...,...
1439,896124,12.500000,20.0,0.062500
1440,12319,4.545455,20.0,0.045455
1441,4421,0.000000,0.0,0.000000
1442,296526,10.000000,20.0,0.050000


In [70]:
import pandas as pd

df_10 = pd.DataFrame({
    "Query_ID": query_ids,
    "recall_10": recall_10_list,
    "precision_10": precision_10_list,
    "AP_10": AP_10_list
})

df_10

,Query_ID,recall_10,precision_10,AP_10
0,123839,100.000000,60.0,0.915079
1,188629,33.333333,20.0,0.333333
2,13898,33.333333,20.0,0.333333
3,316959,22.222222,20.0,0.222222
4,515031,14.285714,20.0,0.095238
...,...,...,...,...
1439,896124,12.500000,10.0,0.062500
1440,12319,4.545455,10.0,0.045455
1441,4421,0.000000,0.0,0.000000
1442,296526,10.000000,10.0,0.050000


In [47]:
import numpy as np
print(f"recall 5 mean: {np.mean(recall_5_list)}")
print(f"precision 5 mean: {np.mean(precision_5_list)}")
print(f"MAP 5: {np.mean(AP_5_list)}")

recall 5 mean: 15.759953800074289
precision 5 mean: 32.841643582640806
MAP 5: 0.12214835351980342


In [53]:
from sklearn.metrics import ndcg_score

doc_id_score_dict = defaultdict(float)
ndcg_5_list = []

for idx in range(len(df)):
    query_id = df.loc[idx, "Query_ID"]
    if query_id in dict_keys_set:
        scoredoc_object_list = score_doc_dict[query_id]

        for scoreddoc_object in scoredoc_object_list:
            doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

        model_score_tuple_list = most_related_5_dict_with_scores[query_id]

        y_score, y_true = [], []

        for mytuple in model_score_tuple_list:
            doc_id = mytuple[0]
            score = mytuple[1]

            y_score.append(score)
            y_true.append(doc_id_score_dict[doc_id])

        if len(y_score) == 0:
            ndcg_5_list.append(0.0)
            continue

        if len(y_score) == 1:
            y_true.append(0.0)
            y_score.append(0.0)

        if len(y_true) == len(y_score):
            ndcg_5_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=5))
        else:
            print("There is a problem with query", query_id)
    else:
        ndcg_5_list.append(0)

In [71]:
from sklearn.metrics import ndcg_score

doc_id_score_dict = defaultdict(float)
ndcg_10_list = []

for idx in range(len(df)):
    query_id = df.loc[idx, "Query_ID"]
    if query_id in dict_keys_set:
        scoredoc_object_list = score_doc_dict[query_id]

        for scoreddoc_object in scoredoc_object_list:
            doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

        model_score_tuple_list = most_related_10_dict_with_scores[query_id]

        y_score, y_true = [], []

        for mytuple in model_score_tuple_list:
            doc_id = mytuple[0]
            score = mytuple[1]

            y_score.append(score)
            y_true.append(doc_id_score_dict[doc_id])

        if len(y_score) == 0:
            ndcg_10_list.append(0.0)
            continue

        if len(y_score) == 1:
            y_true.append(0.0)
            y_score.append(0.0)

        if len(y_true) == len(y_score):
            ndcg_10_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=10))
        else:
            print("There is a problem with query", query_id)
    else:
        ndcg_10_list.append(0)

In [54]:
len(ndcg_5_list)

1444

In [72]:
len(ndcg_10_list)

1444

In [55]:
df["NDCG_5"] = ndcg_5_list
df

,Query_ID,recall_5,precision_5,AP_5,NDCG_5
0,123839,66.666667,80.0,0.500000,0.998041
1,188629,33.333333,40.0,0.333333,0.997851
2,13898,33.333333,40.0,0.333333,0.000000
3,316959,22.222222,40.0,0.222222,0.990788
4,515031,7.142857,20.0,0.071429,0.750615
...,...,...,...,...,...
1439,896124,12.500000,20.0,0.062500,0.989962
1440,12319,4.545455,20.0,0.045455,0.894518
1441,4421,0.000000,0.0,0.000000,0.986699
1442,296526,10.000000,20.0,0.050000,0.698425


In [73]:
df_10["NDCG_10"] = ndcg_10_list
df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10
0,123839,100.000000,60.0,0.915079,0.995386
1,188629,33.333333,20.0,0.333333,0.998514
2,13898,33.333333,20.0,0.333333,0.000000
3,316959,22.222222,20.0,0.222222,0.988966
4,515031,14.285714,20.0,0.095238,0.784951
...,...,...,...,...,...
1439,896124,12.500000,10.0,0.062500,0.990022
1440,12319,4.545455,10.0,0.045455,0.844191
1441,4421,0.000000,0.0,0.000000,0.987909
1442,296526,10.000000,10.0,0.050000,0.717821


In [56]:
df["NDCG_5"].mean()

np.float64(0.8048346515946609)

In [57]:
df["f_score_5"] = 2 * df["recall_5"] * df["precision_5"] / (df["recall_5"] + df["precision_5"])
df

,Query_ID,recall_5,precision_5,AP_5,NDCG_5,f_score_5
0,123839,66.666667,80.0,0.500000,0.998041,72.727273
1,188629,33.333333,40.0,0.333333,0.997851,36.363636
2,13898,33.333333,40.0,0.333333,0.000000,36.363636
3,316959,22.222222,40.0,0.222222,0.990788,28.571429
4,515031,7.142857,20.0,0.071429,0.750615,10.526316
...,...,...,...,...,...,...
1439,896124,12.500000,20.0,0.062500,0.989962,15.384615
1440,12319,4.545455,20.0,0.045455,0.894518,7.407407
1441,4421,0.000000,0.0,0.000000,0.986699,NaN
1442,296526,10.000000,20.0,0.050000,0.698425,13.333333


In [74]:
df_10["f_score_10"] = 2 * df_10["recall_10"] * df_10["precision_10"] / (df_10["recall_10"] + df_10["precision_10"])
df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10,f_score_10
0,123839,100.000000,60.0,0.915079,0.995386,75.000000
1,188629,33.333333,20.0,0.333333,0.998514,25.000000
2,13898,33.333333,20.0,0.333333,0.000000,25.000000
3,316959,22.222222,20.0,0.222222,0.988966,21.052632
4,515031,14.285714,20.0,0.095238,0.784951,16.666667
...,...,...,...,...,...,...
1439,896124,12.500000,10.0,0.062500,0.990022,11.111111
1440,12319,4.545455,10.0,0.045455,0.844191,6.250000
1441,4421,0.000000,0.0,0.000000,0.987909,NaN
1442,296526,10.000000,10.0,0.050000,0.717821,10.000000


In [59]:
df["f_score_5"] = df["f_score_5"].fillna(0)
df.isna().sum()

Query_ID       0
recall_5       0
precision_5    0
AP_5           0
NDCG_5         0
f_score_5      0
dtype: int64

In [75]:
df_10["f_score_10"] = df_10["f_score_10"].fillna(0)
df_10.isna().sum()

Query_ID        0
recall_10       0
precision_10    0
AP_10           0
NDCG_10         0
f_score_10      0
dtype: int64

In [60]:
df

,Query_ID,recall_5,precision_5,AP_5,NDCG_5,f_score_5
0,123839,66.666667,80.0,0.500000,0.998041,72.727273
1,188629,33.333333,40.0,0.333333,0.997851,36.363636
2,13898,33.333333,40.0,0.333333,0.000000,36.363636
3,316959,22.222222,40.0,0.222222,0.990788,28.571429
4,515031,7.142857,20.0,0.071429,0.750615,10.526316
...,...,...,...,...,...,...
1439,896124,12.500000,20.0,0.062500,0.989962,15.384615
1440,12319,4.545455,20.0,0.045455,0.894518,7.407407
1441,4421,0.000000,0.0,0.000000,0.986699,0.000000
1442,296526,10.000000,20.0,0.050000,0.698425,13.333333


In [62]:
mydict = {
    "Method": "BM25 - Lemmatization Cross Encoder",
    "recall_5_mean": df["recall_5"].mean(),
    "recall_5_std": df["recall_5"].std(),
    "recall_5_max": df["recall_5"].max(),
    "recall_5_min": df["recall_5"].min(),
    "precision_5_mean": df["precision_5"].mean(),
    "precision_5_std": df["precision_5"].std(),
    "precision_5_max": df["precision_5"].max(),
    "precision_5_min": df["precision_5"].min(),
    "f_score_5_mean": df["f_score_5"].mean(),
    "f_score_5_std": df["f_score_5"].std(),
    "f_score_5_max": df["f_score_5"].max(),
    "f_score_5_min": df["f_score_5"].min(),
    "MAP_5": df["AP_5"].mean(),
    "NDCG_5_mean": df["NDCG_5"].mean(),
    "NDCG_5_std": df["NDCG_5"].std(),
    "NDCG_5_max": df["NDCG_5"].max(),
    "NDCG_5_min": df["NDCG_5"].min(),
}

In [77]:
mydict = {
    "Method": "BM25 - Lemmatization Cross Encoder",
    "recall_10_mean": df_10["recall_10"].mean(),
    "recall_10_std": df_10["recall_10"].std(),
    "recall_10_max": df_10["recall_10"].max(),
    "recall_10_min": df_10["recall_10"].min(),
    "precision_10_mean": df_10["precision_10"].mean(),
    "precision_10_std": df_10["precision_10"].std(),
    "precision_10_max": df_10["precision_10"].max(),
    "precision_10_min": df_10["precision_10"].min(),
    "f_score_10_mean": df_10["f_score_10"].mean(),
    "f_score_10_std": df_10["f_score_10"].std(),
    "f_score_10_max": df_10["f_score_10"].max(),
    "f_score_10_min": df_10["f_score_10"].min(),
    "MAP_10": df_10["AP_10"].mean(),
    "NDCG_10_mean": df_10["NDCG_10"].mean(),
    "NDCG_10_std": df_10["NDCG_10"].std(),
    "NDCG_10_max": df_10["NDCG_10"].max(),
    "NDCG_10_min": df_10["NDCG_10"].min(),
}

In [63]:
df_parquet = pd.DataFrame(mydict, index=[0])
df_parquet

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,precision_5_mean,precision_5_std,precision_5_max,precision_5_min,f_score_5_mean,f_score_5_std,f_score_5_max,f_score_5_min,MAP_5,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min
0,BM25 - Lemmatization Cross Encoder,15.759954,14.439942,83.333333,0.0,32.841644,23.152133,100.0,0.0,19.776504,16.665978,90.909091,0.0,0.122148,0.804835,0.327528,1.0,0.0


In [78]:
df_parquet_10 = pd.DataFrame(mydict, index=[0])
df_parquet_10

,Method,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_10_mean,precision_10_std,precision_10_max,precision_10_min,f_score_10_mean,f_score_10_std,f_score_10_max,f_score_10_min,MAP_10,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,BM25 - Lemmatization Cross Encoder,20.86522,19.584312,100.0,0.0,22.903311,17.788971,100.0,0.0,19.673399,16.680059,100.0,0.0,0.153571,0.811885,0.291716,1.0,0.0


In [64]:
df_parquet.to_parquet("BM25LemmatizationCrossEncoder.parquet")

In [3]:
mydict_final = {
    "Method": "BM25 - Lemmatization Cross Encoder",
    "recall_5_mean": 15.759954,
    "recall_5_std": 14.439942,
    "recall_5_max": 83.333333,
    "recall_5_min": 0.0,
    "precision_5_mean": 32.841644,
    "precision_5_std": 23.152133,
    "precision_5_max": 100.0,
    "precision_5_min": 0.0,
    "f_score_5_mean": 19.776504,
    "f_score_5_std": 16.665978,
    "f_score_5_max": 90.909091,
    "f_score_5_min": 0.0,
    "MAP_5": 0.122148,
    "NDCG_5_mean": 0.804835,
    "NDCG_5_std": 0.327528,
    "NDCG_5_max": 1.0,
    "NDCG_5_min": 0.0,
    "recall_10_mean": 20.86522,
    "recall_10_std": 19.584312,
    "recall_10_max": 100.0,
    "recall_10_min": 0.0,
    "precision_10_mean": 22.903311,
    "precision_10_std": 17.788971,
    "precision_10_max": 100.0,
    "precision_10_min": 0.0,
    "f_score_10_mean": 19.673399,
    "f_score_10_std": 16.680059,
    "f_score_10_max": 100.0,
    "f_score_10_min": 0.0,
    "MAP_10": 0.153571,
    "NDCG_10_mean": 0.811885,
    "NDCG_10_std": 0.291716,
    "NDCG_10_max": 1.0,
    "NDCG_10_min": 0.0
}

In [4]:
import pandas as pd
df_final = pd.DataFrame(mydict_final, index=[0])
df_final

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,precision_5_mean,precision_5_std,precision_5_max,precision_5_min,f_score_5_mean,...,precision_10_min,f_score_10_mean,f_score_10_std,f_score_10_max,f_score_10_min,MAP_10,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,BM25 - Lemmatization Cross Encoder,15.759954,14.439942,83.333333,0.0,32.841644,23.152133,100.0,0.0,19.776504,...,0.0,19.673399,16.680059,100.0,0.0,0.153571,0.811885,0.291716,1.0,0.0


In [5]:
df_final.to_parquet("BM25LemmatizationCrossEncoder.parquet")