In [1]:
import ir_datasets
from nltk.stem import WordNetLemmatizer
import nltk
from helper import create_tokenized_word_list

dataset = ir_datasets.load("wikir/en1k/training")
tokenized = create_tokenized_word_list(dataset)

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
nltk.download("punkt_tab")
nltk.download("wordnet")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /home/tahas44/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [3]:
lemmatized_tokenized_docs = []
lematizer = WordNetLemmatizer()

for query_list in tokenized:
    lemmatized_words = [lematizer.lemmatize(word) for word in query_list]
    lemmatized_tokenized_docs.append(lemmatized_words)

print("Docs lemmatized")

Docs lemmatized


In [4]:
from helper import create_tokenized_word_list_for_query
query_tokenized = create_tokenized_word_list_for_query(dataset)
print("Queries tokenized!")

Queries tokenized!


[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [5]:
lemmatized_tokenized_queries = []

for query_list in query_tokenized:
    lemmatized_words = [lematizer.lemmatize(words) for words in query_list]
    lemmatized_tokenized_queries.append(lemmatized_words)

print("Queries lemmatized")

Queries lemmatized


In [6]:
lemmatized_tokenized_queries

[['yanni'],
 ['k', 'pop'],
 ['venice', 'film', 'festival'],
 ['downtown', 'brooklyn'],
 ['pennsylvania', 'house', 'representative'],
 ['northern', 'premier', 'league'],
 ['first', 'national', 'picture'],
 ['poland'],
 ['cyperaceae'],
 ['trinidad', 'tobago'],
 ['normandy', 'landing'],
 ['perry', 'index'],
 ['arm', 'architecture'],
 ['mi5'],
 ['patriarch', 'antioch'],
 ['nashik', 'district'],
 ['semiotics'],
 ['santa', 'cruz', 'de', 'tenerife'],
 ['gastropoda'],
 ['zaragoza'],
 ['south', 'carolina'],
 ['augustine', 'hippo'],
 ['canton', 'geneva'],
 ['leo', 'tolstoy'],
 ['riemannian', 'manifold'],
 ['tuzla'],
 ['subaru'],
 ['tomsk'],
 ['united', 'state', 'department', 'agriculture'],
 ['north', 'borneo'],
 ['isaac', 'asimov'],
 ['hilbert', 'space'],
 ['chechen'],
 ['arunachal', 'pradesh'],
 ['central', 'otago'],
 ['ira', 'gershwin'],
 ['rock', 'roll'],
 ['fiba'],
 ['east', 'coast', 'united', 'state'],
 ['wikipedia'],
 ['pernambuco'],
 ['west', 'coast', 'eagle'],
 ['twin', 'peak'],
 ['dutc

In [7]:
from nltk.wsd import lesk

lesked_queries = []

for query_list in lemmatized_tokenized_queries:
    query_weighted_lesk = []
    none_lesk_list = []
    isLesk = False

    for word in query_list:
        temp = lesk(query_list, word)

        if temp is None:
            none_lesk_list.append(word)
        else:
            isLesk = True
            query_weighted_lesk.extend([word] * 2)
            cleaned_lemmas = [lemma.replace('_', ' ') for lemma in temp.lemma_names()]
            query_weighted_lesk.extend(cleaned_lemmas)

    if none_lesk_list:
        if isLesk:
            for anyword in none_lesk_list:
                query_weighted_lesk.extend([anyword] * 2)
        else:
            query_weighted_lesk.extend(none_lesk_list)

    lesked_queries.append(query_weighted_lesk)

In [8]:
lesked_queries

[['yanni'],
 ['k', 'k', 'kelvin', 'K', 'pop', 'pop', 'pop'],
 ['venice',
  'venice',
  'Venice',
  'Venezia',
  'film',
  'film',
  'film',
  'shoot',
  'take',
  'festival',
  'festival',
  'festival'],
 ['downtown',
  'downtown',
  'business district',
  'downtown',
  'brooklyn',
  'brooklyn',
  'Brooklyn'],
 ['pennsylvania',
  'pennsylvania',
  'Pennsylvania',
  'Keystone State',
  'PA',
  'house',
  'house',
  'house',
  'representative',
  'representative',
  'representative'],
 ['northern',
  'northern',
  'Northern',
  'premier',
  'premier',
  'Prime Minister',
  'PM',
  'premier',
  'league',
  'league',
  'league'],
 ['first',
  'first',
  'first',
  'number one',
  'national',
  'national',
  'national',
  'picture',
  'picture',
  'picture',
  'depict',
  'render',
  'show'],
 ['poland', 'poland', 'Poland', 'Republic of Poland', 'Polska'],
 ['cyperaceae',
  'cyperaceae',
  'Cyperaceae',
  'family Cyperaceae',
  'sedge family'],
 ['trinidad', 'trinidad', 'Trinidad', 'tobago'

In [9]:
lemmatized_tokenized_queries

[['yanni'],
 ['k', 'pop'],
 ['venice', 'film', 'festival'],
 ['downtown', 'brooklyn'],
 ['pennsylvania', 'house', 'representative'],
 ['northern', 'premier', 'league'],
 ['first', 'national', 'picture'],
 ['poland'],
 ['cyperaceae'],
 ['trinidad', 'tobago'],
 ['normandy', 'landing'],
 ['perry', 'index'],
 ['arm', 'architecture'],
 ['mi5'],
 ['patriarch', 'antioch'],
 ['nashik', 'district'],
 ['semiotics'],
 ['santa', 'cruz', 'de', 'tenerife'],
 ['gastropoda'],
 ['zaragoza'],
 ['south', 'carolina'],
 ['augustine', 'hippo'],
 ['canton', 'geneva'],
 ['leo', 'tolstoy'],
 ['riemannian', 'manifold'],
 ['tuzla'],
 ['subaru'],
 ['tomsk'],
 ['united', 'state', 'department', 'agriculture'],
 ['north', 'borneo'],
 ['isaac', 'asimov'],
 ['hilbert', 'space'],
 ['chechen'],
 ['arunachal', 'pradesh'],
 ['central', 'otago'],
 ['ira', 'gershwin'],
 ['rock', 'roll'],
 ['fiba'],
 ['east', 'coast', 'united', 'state'],
 ['wikipedia'],
 ['pernambuco'],
 ['west', 'coast', 'eagle'],
 ['twin', 'peak'],
 ['dutc

In [10]:
from rank_bm25 import BM25Okapi
bm25 = BM25Okapi(lemmatized_tokenized_docs)

In [11]:
scores_of_all_queries = []

for query in lesked_queries:
    scores_of_all_queries.append(bm25.get_scores(query))

In [12]:
from collections import defaultdict
from helper import Scoredoc

doc_dict = defaultdict(str)

for i, doc in enumerate(dataset.docs_iter()):
    doc_dict[i] = doc.doc_id

doc_dict = dict(doc_dict)

qrels_dict = defaultdict(list)

for qrel in dataset.qrels_iter():
    qrels_dict[qrel.query_id].append(qrel.doc_id)

qrels_dict = dict(qrels_dict)

score_doc_dict = defaultdict(list)

for scoreddoc in dataset.scoreddocs_iter():
    doc_id = scoreddoc.doc_id
    score = scoreddoc.score

    scoreddoc_object = Scoredoc(doc_id, score)

    score_doc_dict[scoreddoc.query_id].append(scoreddoc_object)

score_doc_dict = dict(score_doc_dict)

print("Necessary dicts created!")

Necessary dicts created!


In [13]:
query_ids = [query.query_id for query in dataset.queries_iter()]
query_ids

['123839',
 '188629',
 '13898',
 '316959',
 '515031',
 '123783',
 '4332',
 '9591',
 '114982',
 '563603',
 '104206',
 '1580851',
 '23678',
 '37480',
 '109454',
 '544250',
 '12519',
 '115015',
 '84287',
 '24998',
 '11925',
 '643',
 '113075',
 '1250387',
 '72012',
 '167865',
 '1425120',
 '24883',
 '27200',
 '136856',
 '6031',
 '1313191',
 '187115',
 '84110',
 '208234',
 '6431',
 '10799',
 '1417144',
 '32512',
 '677637',
 '97937',
 '113765',
 '12900',
 '1294909',
 '73745',
 '11692',
 '22173',
 '76662',
 '164301',
 '23344',
 '9367',
 '592217',
 '98546',
 '98175',
 '15189',
 '1256',
 '1815937',
 '1249076',
 '80274',
 '38489',
 '11311',
 '4754',
 '257711',
 '141668',
 '100895',
 '32945',
 '112321',
 '133725',
 '424464',
 '523456',
 '1327515',
 '12101',
 '9739',
 '189869',
 '143444',
 '78940',
 '12527',
 '327199',
 '7707',
 '97455',
 '1262433',
 '488875',
 '74026',
 '358108',
 '95179',
 '7862',
 '151797',
 '92980',
 '100876',
 '238228',
 '107755',
 '32539',
 '12953',
 '24843',
 '119528',
 '307

In [14]:
scores_of_all_queries

[array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 7.71542974, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([ 0.        ,  0.        , 34.63292927, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 3.90094591, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([14.65602297,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 3.74912202,
        0.        ]

In [15]:
from collections import defaultdict

query_id_vs_text = defaultdict(str)

for query in dataset.queries_iter():
    query_id_vs_text[query.query_id] = query.text

In [16]:
import gc
del dataset
del tokenized
del lematizer
del bm25
gc.collect()

0

In [17]:
del lemmatized_tokenized_docs
del lemmatized_tokenized_queries
del lemmatized_words
del query_tokenized
gc.collect()

0

In [18]:
import numpy as np
query_id_and_its_doc_for_10 = defaultdict(list)

for i in range(len(query_ids)):
    found_doc_list = []
    similarity = scores_of_all_queries[i]

    index_of_found_docs = np.where(similarity > 0)[0]

    for index in list(index_of_found_docs):
        found_doc_list.append((similarity[index], doc_dict[index]))

    if len(found_doc_list) <= 10:
        for mytuple in found_doc_list:
            query_id_and_its_doc_for_10[query_ids[i]].append(mytuple[1])
    else:
        for mytuple in sorted(found_doc_list, reverse=True):
            query_id_and_its_doc_for_10[query_ids[i]].append(mytuple[1])

            if len(query_id_and_its_doc_for_10[query_ids[i]]) == 10:
                break

In [19]:
query_id_and_its_doc_for_10

defaultdict(list,
            {'123839': ['806300',
              '123839',
              '806326',
              '836567',
              '806075',
              '1793430',
              '806263',
              '799188',
              '1727316',
              '1901730'],
             '188629': ['188629',
              '2191096',
              '2185399',
              '2304431',
              '1046396',
              '1990307',
              '2296288',
              '2290269',
              '533438',
              '62956'],
             '13898': ['13898',
              '2336616',
              '1921403',
              '1874948',
              '2213954',
              '2108627',
              '2248373',
              '525283',
              '2216860',
              '1453647'],
             '316959': ['316959',
              '348869',
              '1836641',
              '2156815',
              '1326263',
              '930698',
              '395421',
              '918373',
         

In [21]:
import ir_datasets

dataset = ir_datasets.load("wikir/en1k/training")
doc_id_vs_text = defaultdict(str)

for doc in dataset.docs_iter():
    doc_id_vs_text[doc.doc_id] = doc.text

In [22]:
query_doc_pairs = defaultdict(list)

for query_id in query_ids:
    for doc_id in query_id_and_its_doc_for_10[query_id]:
        query_doc_pairs[query_id].append((query_id_vs_text[query_id], doc_id_vs_text[doc_id]))

In [23]:
query_doc_pairs["123839"]

[('yanni',
  'it is a compilation of tracks from his five previous studio albums released between 1980 and 1989 plus three new compositions yanni was encouraged to release the album by his then partner actress linda evans reflections of passion became yanni s fastest selling and most successful album of his career upon release it reached no 1 on the billboard top new age albums chart and no 29 on the billboard 200 yanni supported the album with a nationwide concert tour in 1990 that featured his band and an orchestra in 1995 it was certified double platinum for selling 2 million copies in the us in august 1989 yanni released his fifth studio album niki nana the album marked his stylistic development from solo keyboard music towards rock with the addition of additional vocalists musicians and choir around the same time of its release yanni s newfound relationship with american actress linda evans who had become a fan of his music received press attention not long into their relationship

In [24]:
len(query_doc_pairs.keys())

1442

In [25]:
from sentence_transformers import CrossEncoder
model = CrossEncoder('cross-encoder/ms-marco-MiniLM-L6-v2')

/run/media/tahas44/Yeni Birim/Technarts/Intern/NLP/InformationRetrieval/.venv/lib64/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 2560.42it/s]


In [26]:
dict_keys_set = set(query_doc_pairs.keys())

In [27]:
query_score_dict = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        query_score_dict[query_id] = list(model.predict(query_doc_pairs[query_id]))

In [28]:
query_score_dict["123839"]

[np.float32(6.4627924),
 np.float32(6.419842),
 np.float32(4.9677753),
 np.float32(3.0357656),
 np.float32(5.5189133),
 np.float32(2.3268332),
 np.float32(4.384878),
 np.float32(0.7513137),
 np.float32(-3.6361036),
 np.float32(-4.7235107)]

In [29]:
del query_doc_pairs 
gc.collect()

271

In [30]:
most_related_10_dict = defaultdict(list)
most_related_10_dict_with_scores = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        related_10 = []

        for i, score in enumerate(query_score_dict[query_id]):
            related_10.append((score, i))

        for mytuple in sorted(related_10, reverse=True):
            most_related_10_dict[query_id].append(query_id_and_its_doc_for_10[query_id][mytuple[1]])
            most_related_10_dict_with_scores[query_id].append((query_id_and_its_doc_for_10[query_id][mytuple[1]], mytuple[0]))

            if len(most_related_10_dict[query_id]) == 10:
                break

In [31]:
def recall(found_docs: list, test_list: list) -> float:
    counter = 0
    test_set = set(test_list)

    for doc_id in found_docs:
        if doc_id in test_set:
            counter += 1

    return (counter / len(test_list)) * 100

def precision(found_docs: list, test_list: list) -> float:
    counter = 0
    test_set = set(test_list)

    for doc_id in found_docs:
        if doc_id in test_set:
            counter += 1

    return (counter / len(found_docs)) * 100

def precision_AP(found_docs: list, test_list: list) -> float:
    counter = 0

    test_set = set(test_list)

    for doc in found_docs:
        if doc in test_set:
            counter += 1

    return counter / len(found_docs)


def AP(found_docs: list, test_list: list) -> float:
    total = 0

    for i in range(1, 10 + 1):
        if i < len(found_docs):
            precision_k = precision_AP(found_docs[:i], test_list)
            total += precision_k * (found_docs[i - 1] in set(test_list))

    return total / len(test_list)

In [32]:
recall_10_list, precision_10_list, AP_10_list = [], [], []

for query_id in query_ids:
    if query_id in dict_keys_set:
        recall_10_value = recall(most_related_10_dict[query_id], qrels_dict[query_id])
        precision_10_value = precision(most_related_10_dict[query_id], qrels_dict[query_id])
        AP_10_value = AP(most_related_10_dict[query_id], qrels_dict[query_id])

        recall_10_list.append(recall_10_value)
        precision_10_list.append(precision_10_value)
        AP_10_list.append(AP_10_value)
    else:
        recall_10_list.append(0)
        precision_10_list.append(0)
        AP_10_list.append(0)

In [33]:
len(recall_10_list)

1444

In [34]:
import pandas as pd

df_10 = pd.DataFrame({
    "Query_ID": query_ids,
    "recall_10": recall_10_list,
    "precision_10": precision_10_list,
    "AP_10": AP_10_list
})

df_10

,Query_ID,recall_10,precision_10,AP_10
0,123839,100.000000,60.0,0.915079
1,188629,33.333333,20.0,0.333333
2,13898,33.333333,20.0,0.333333
3,316959,22.222222,20.0,0.222222
4,515031,14.285714,20.0,0.100000
...,...,...,...,...
1439,896124,12.500000,10.0,0.062500
1440,12319,4.545455,10.0,0.045455
1441,4421,0.000000,0.0,0.000000
1442,296526,0.000000,0.0,0.000000


In [35]:
from sklearn.metrics import ndcg_score

doc_id_score_dict = defaultdict(float)
ndcg_10_list = []

for idx in range(len(df_10)):
    query_id = df_10.loc[idx, "Query_ID"]
    if query_id in dict_keys_set:
        scoredoc_object_list = score_doc_dict[query_id]

        for scoreddoc_object in scoredoc_object_list:
            doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

        model_score_tuple_list = most_related_10_dict_with_scores[query_id]

        y_score, y_true = [], []

        for mytuple in model_score_tuple_list:
            doc_id = mytuple[0]
            score = mytuple[1]

            y_score.append(score)
            y_true.append(doc_id_score_dict[doc_id])

        if len(y_score) == 0:
            ndcg_10_list.append(0.0)
            continue

        if len(y_score) == 1:
            y_true.append(0.0)
            y_score.append(0.0)

        if len(y_true) == len(y_score):
            ndcg_10_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=10))
        else:
            print("There is a problem with query", query_id)
    else:
        ndcg_10_list.append(0)

In [36]:
len(ndcg_10_list)

1444

In [37]:
df_10["NDCG_10"] = ndcg_10_list
df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10
0,123839,100.000000,60.0,0.915079,0.995386
1,188629,33.333333,20.0,0.333333,0.998342
2,13898,33.333333,20.0,0.333333,0.000000
3,316959,22.222222,20.0,0.222222,0.991666
4,515031,14.285714,20.0,0.100000,0.760507
...,...,...,...,...,...
1439,896124,12.500000,10.0,0.062500,0.990022
1440,12319,4.545455,10.0,0.045455,0.775022
1441,4421,0.000000,0.0,0.000000,0.990301
1442,296526,0.000000,0.0,0.000000,0.693317


In [38]:
df_10["f_score_10"] = 2 * df_10["recall_10"] * df_10["precision_10"] / (df_10["recall_10"] + df_10["precision_10"])
df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10,f_score_10
0,123839,100.000000,60.0,0.915079,0.995386,75.000000
1,188629,33.333333,20.0,0.333333,0.998342,25.000000
2,13898,33.333333,20.0,0.333333,0.000000,25.000000
3,316959,22.222222,20.0,0.222222,0.991666,21.052632
4,515031,14.285714,20.0,0.100000,0.760507,16.666667
...,...,...,...,...,...,...
1439,896124,12.500000,10.0,0.062500,0.990022,11.111111
1440,12319,4.545455,10.0,0.045455,0.775022,6.250000
1441,4421,0.000000,0.0,0.000000,0.990301,NaN
1442,296526,0.000000,0.0,0.000000,0.693317,NaN


In [40]:
df_10["f_score_10"] = df_10["f_score_10"].fillna(0)

In [41]:
df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10,f_score_10
0,123839,100.000000,60.0,0.915079,0.995386,75.000000
1,188629,33.333333,20.0,0.333333,0.998342,25.000000
2,13898,33.333333,20.0,0.333333,0.000000,25.000000
3,316959,22.222222,20.0,0.222222,0.991666,21.052632
4,515031,14.285714,20.0,0.100000,0.760507,16.666667
...,...,...,...,...,...,...
1439,896124,12.500000,10.0,0.062500,0.990022,11.111111
1440,12319,4.545455,10.0,0.045455,0.775022,6.250000
1441,4421,0.000000,0.0,0.000000,0.990301,0.000000
1442,296526,0.000000,0.0,0.000000,0.693317,0.000000


In [42]:
query_doc_pairs = defaultdict(list)

for query_id in query_ids:
    for doc_id in query_id_and_its_doc_for_10[query_id]:
        query_doc_pairs[query_id].append((query_id_vs_text[query_id], doc_id_vs_text[doc_id]))

In [43]:
most_related_5_dict = defaultdict(list)
most_related_5_dict_with_scores = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        related_10 = []

        for i, score in enumerate(query_score_dict[query_id]):
            related_10.append((score, i))

        for mytuple in sorted(related_10, reverse=True):
            most_related_5_dict[query_id].append(query_id_and_its_doc_for_10[query_id][mytuple[1]])
            most_related_5_dict_with_scores[query_id].append((query_id_and_its_doc_for_10[query_id][mytuple[1]], mytuple[0]))

            if len(most_related_5_dict[query_id]) == 5:
                break

In [44]:
recall_5_list, precision_5_list, AP_5_list = [], [], []

for query_id in query_ids:
    if query_id in dict_keys_set:
        recall_5_value = recall(most_related_5_dict[query_id], qrels_dict[query_id])
        precision_5_value = precision(most_related_5_dict[query_id], qrels_dict[query_id])
        AP_5_value = AP(most_related_5_dict[query_id], qrels_dict[query_id])

        recall_5_list.append(recall_5_value)
        precision_5_list.append(precision_5_value)
        AP_5_list.append(AP_5_value)
    else:
        recall_5_list.append(0)
        precision_5_list.append(0)
        AP_5_list.append(0)

In [45]:
df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10,f_score_10
0,123839,100.000000,60.0,0.915079,0.995386,75.000000
1,188629,33.333333,20.0,0.333333,0.998342,25.000000
2,13898,33.333333,20.0,0.333333,0.000000,25.000000
3,316959,22.222222,20.0,0.222222,0.991666,21.052632
4,515031,14.285714,20.0,0.100000,0.760507,16.666667
...,...,...,...,...,...,...
1439,896124,12.500000,10.0,0.062500,0.990022,11.111111
1440,12319,4.545455,10.0,0.045455,0.775022,6.250000
1441,4421,0.000000,0.0,0.000000,0.990301,0.000000
1442,296526,0.000000,0.0,0.000000,0.693317,0.000000


In [46]:
df_10["recall_5"] = recall_5_list
df_10["precision_5"] = precision_5_list
df_10["AP_5"] = AP_5_list

In [47]:
df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10,f_score_10,recall_5,precision_5,AP_5
0,123839,100.000000,60.0,0.915079,0.995386,75.000000,66.666667,80.0,0.500000
1,188629,33.333333,20.0,0.333333,0.998342,25.000000,33.333333,40.0,0.333333
2,13898,33.333333,20.0,0.333333,0.000000,25.000000,33.333333,40.0,0.333333
3,316959,22.222222,20.0,0.222222,0.991666,21.052632,22.222222,40.0,0.222222
4,515031,14.285714,20.0,0.100000,0.760507,16.666667,14.285714,40.0,0.071429
...,...,...,...,...,...,...,...,...,...
1439,896124,12.500000,10.0,0.062500,0.990022,11.111111,12.500000,20.0,0.062500
1440,12319,4.545455,10.0,0.045455,0.775022,6.250000,4.545455,20.0,0.045455
1441,4421,0.000000,0.0,0.000000,0.990301,0.000000,0.000000,0.0,0.000000
1442,296526,0.000000,0.0,0.000000,0.693317,0.000000,0.000000,0.0,0.000000


In [48]:
df_10["f_score_5"] = 2 * df_10["recall_5"] * df_10["precision_5"] / (df_10["recall_5"] + df_10["precision_5"])

In [49]:
df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10,f_score_10,recall_5,precision_5,AP_5,f_score_5
0,123839,100.000000,60.0,0.915079,0.995386,75.000000,66.666667,80.0,0.500000,72.727273
1,188629,33.333333,20.0,0.333333,0.998342,25.000000,33.333333,40.0,0.333333,36.363636
2,13898,33.333333,20.0,0.333333,0.000000,25.000000,33.333333,40.0,0.333333,36.363636
3,316959,22.222222,20.0,0.222222,0.991666,21.052632,22.222222,40.0,0.222222,28.571429
4,515031,14.285714,20.0,0.100000,0.760507,16.666667,14.285714,40.0,0.071429,21.052632
...,...,...,...,...,...,...,...,...,...,...
1439,896124,12.500000,10.0,0.062500,0.990022,11.111111,12.500000,20.0,0.062500,15.384615
1440,12319,4.545455,10.0,0.045455,0.775022,6.250000,4.545455,20.0,0.045455,7.407407
1441,4421,0.000000,0.0,0.000000,0.990301,0.000000,0.000000,0.0,0.000000,NaN
1442,296526,0.000000,0.0,0.000000,0.693317,0.000000,0.000000,0.0,0.000000,NaN


In [51]:
from sklearn.metrics import ndcg_score

doc_id_score_dict = defaultdict(float)
ndcg_5_list = []

for idx in range(len(df_10)):
    query_id = df_10.loc[idx, "Query_ID"]
    if query_id in dict_keys_set:
        scoredoc_object_list = score_doc_dict[query_id]

        for scoreddoc_object in scoredoc_object_list:
            doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

        model_score_tuple_list = most_related_5_dict_with_scores[query_id]

        y_score, y_true = [], []

        for mytuple in model_score_tuple_list:
            doc_id = mytuple[0]
            score = mytuple[1]

            y_score.append(score)
            y_true.append(doc_id_score_dict[doc_id])

        if len(y_score) == 0:
            ndcg_5_list.append(0.0)
            continue

        if len(y_score) == 1:
            y_true.append(0.0)
            y_score.append(0.0)

        if len(y_true) == len(y_score):
            ndcg_5_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=5))
        else:
            print("There is a problem with query", query_id)
    else:
        ndcg_5_list.append(0)

In [52]:
df_10["NDCG_5"] = ndcg_5_list

In [53]:
df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10,f_score_10,recall_5,precision_5,AP_5,f_score_5,NDCG_5
0,123839,100.000000,60.0,0.915079,0.995386,75.000000,66.666667,80.0,0.500000,72.727273,0.998041
1,188629,33.333333,20.0,0.333333,0.998342,25.000000,33.333333,40.0,0.333333,36.363636,0.997851
2,13898,33.333333,20.0,0.333333,0.000000,25.000000,33.333333,40.0,0.333333,36.363636,0.000000
3,316959,22.222222,20.0,0.222222,0.991666,21.052632,22.222222,40.0,0.222222,28.571429,0.989511
4,515031,14.285714,20.0,0.100000,0.760507,16.666667,14.285714,40.0,0.071429,21.052632,0.754046
...,...,...,...,...,...,...,...,...,...,...,...
1439,896124,12.500000,10.0,0.062500,0.990022,11.111111,12.500000,20.0,0.062500,15.384615,0.989962
1440,12319,4.545455,10.0,0.045455,0.775022,6.250000,4.545455,20.0,0.045455,7.407407,0.840926
1441,4421,0.000000,0.0,0.000000,0.990301,0.000000,0.000000,0.0,0.000000,NaN,0.986912
1442,296526,0.000000,0.0,0.000000,0.693317,0.000000,0.000000,0.0,0.000000,NaN,0.674780


In [54]:
mydict = {
    "Method": "BM25 - Lemmatization Cross Encoder With Query Expansion",
    "recall_5_mean": df_10["recall_5"].mean(),
    "recall_5_std": df_10["recall_5"].std(),
    "recall_5_max": df_10["recall_5"].max(),
    "recall_5_min": df_10["recall_5"].min(),
    "recall_10_mean": df_10["recall_10"].mean(),
    "recall_10_std": df_10["recall_10"].std(),
    "recall_10_max": df_10["recall_10"].max(),
    "recall_10_min": df_10["recall_10"].min(),
    "precision_5_mean": df_10["precision_5"].mean(),
    "precision_5_std": df_10["precision_5"].std(),
    "precision_5_max": df_10["precision_5"].max(),
    "precision_5_min": df_10["precision_5"].min(),
    "precision_10_mean": df_10["precision_10"].mean(),
    "precision_10_std": df_10["precision_10"].std(),
    "precision_10_max": df_10["precision_10"].max(),
    "precision_10_min": df_10["precision_10"].min(),
    "f_score_5_mean": df_10["f_score_5"].mean(),
    "f_score_5_std": df_10["f_score_5"].std(),
    "f_score_5_max": df_10["f_score_5"].max(),
    "f_score_5_min": df_10["f_score_5"].min(),
    "f_score_10_mean": df_10["f_score_10"].mean(),
    "f_score_10_std": df_10["f_score_10"].std(),
    "f_score_10_max": df_10["f_score_10"].max(),
    "f_score_10_min": df_10["f_score_10"].min(),
    "MAP_5": df_10["AP_5"].mean(),
    "MAP_10": df_10["AP_10"].mean(),
    "NDCG_5_mean": df_10["NDCG_5"].mean(),
    "NDCG_5_std": df_10["NDCG_5"].std(),
    "NDCG_5_max": df_10["NDCG_5"].max(),
    "NDCG_5_min": df_10["NDCG_5"].min(),
    "NDCG_10_mean": df_10["NDCG_10"].mean(),
    "NDCG_10_std": df_10["NDCG_10"].std(),
    "NDCG_10_max": df_10["NDCG_10"].max(),
    "NDCG_10_min": df_10["NDCG_10"].min()
}

In [55]:
df_parquet = pd.DataFrame(mydict, index=[0])
df_parquet

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,BM25 - Lemmatization Cross Encoder With Query ...,15.642264,14.4619,83.333333,0.0,20.540319,19.448146,100.0,0.0,32.523084,...,0.121822,0.152152,0.804181,0.326229,1.0,0.0,0.81125,0.289479,1.0,0.0


In [56]:
df_parquet.to_parquet("BM25LemmatizationCrossEncoderWithQueryExpansion.parquet")